os: linux
dist: bionic

language: python
python: 3.7

env:
   - BUILD_SHARED_LIBS=OFF WITH_MPI=ON
   - BUILD_SHARED_LIBS=ON WITH_MPI=ON
   - BUILD_SHARED_LIBS=OFF WITH_MPI=OFF
   - BUILD_SHARED_LIBS=ON WITH_MPI=OFF

addons:
   apt:
      packages:
      - cmake
      - build-essential
      - gfortran
      - libblas-dev
      - liblapack-dev
      - python3
      - python3-pip
      - libopenmpi-dev
      - libscalapack-openmpi-dev

install:
- pip3 install fypp

script:
- cd ${TRAVIS_BUILD_DIR} && mkdir _build && cd _build
- cmake -DWITH_MPI=${WITH_MPI} -DBUILD_SHARED_LIBS=${BUILD_SHARED_LIBS} -DBUILD_TESTING=ON ..
- make
- ctest
